import {Categories} from './globalTypes';

const data: Categories = {
  offers: [
    {
      id: 1,
      price: '13,990',
      name: 'BINGSTA',
      image: require('../assets/images/products/offers/couch1.png'),
      uid: '004.542.32',
      category: 'Armchair',
      type: 'Armchair, Vissle dark grey/Kabusa dark grey',
      short_desc:
        'With its curved and embracing back panel, BINGSTA armchair allows you to have well-needed me time in a private nook – even in open-plan environments.',
      desc: 'Soft, rounded armrests and back cushion provide you with your own comfortable nook which feels snug thanks to the solid and curved back panel.',
    },
    {
      id: 2,
      name: 'BILLY',
      image: require('../assets/images/products/offers/pic2.png'),
      uid: '605.086.42',
      category: 'Bookcases',
      desc: 'BILLY is a versatile bookcase that works just as good as a storage unit and is suitable to use in many different ways at home.',
      price: '4,790',
      short_desc:
        'BILLY bookcase is a beloved icon that never goes out of style. Thanks to its versatility you can use it in many different ways at home – regardless of whether you store books or everyday items in it.',
      type: 'Bookcase, brown walnut effect',
    },
    {
      id: 3,
      name: 'POÄNG',
      image: require('../assets/images/products/offers/pic3.png'),
      uid: '294.291.81',
      category: 'Armchair',
      desc: 'A range of various seat cushions makes it easy to change the look of your POÄNG and your living room. The high back gives good support for your neck.',
      price: '11,990',
      short_desc:
        'The layer-glued bent wood frame gives the armchair a comfortable resilience, making it perfect to relax in.',
      type: 'Rocking-chair, brown/Hillared beige',
    },
    {
      id: 4,
      name: 'SANDARED',
      image: require('../assets/images/products/offers/pic4.png'),
      type: 'Pouffe, beige, 45 cm (17 3/4 ")',
      category: 'Footstool',
      price: '3,990',
      short_desc:
        'This soft and beautiful pouffe can be used as a footstool or extra seat. It is available in three sizes with knitted covers in different colours and patterns – perfect on their own or together!',
      uid: '703.853.15',
      desc: 'SANDARED pouffes are available in three sizes. They have soft, knitted covers in different colours and patterns. Use them on their own or together in a personal combination.',
    },
    {
      id: 5,
      name: 'LAGKAPTEN / ALEX',
      image: require('../assets/images/products/offers/pic5.png'),
      type: 'Desk, black-brown/black',
      price: '9,990',
      category: 'Table & desk system',
      short_desc:
        'Limited space doesn’t mean you have to say no to studying or working from home. This desk takes up little floor space yet still has a drawer unit where you can store papers and other important things.',
      uid: '694.170.58',
      desc: 'The tabletop has pre-drilled holes to make it easier to attach to the underframe.',
    },
    {
      id: 6,
      name: 'LÅNGFJÄLL',
      image: require('../assets/images/products/offers/pic6.png'),
      type: 'Conference chair with armrests, Gunnared light brown-pink/white',
      price: '13,990',
      category: 'Desk Chairs',
      short_desc:
        'The gently curved lines accentuated by sewn details are kind to your body and pleasant to look at. Also, there’s a tilt and height-adjusting mechanism that’s built to outlast years of ups and downs.',
      uid: '892.527.87',
      desc: 'An office chair with lightly curved lines, attention to the sewn details and an easy-to-use mechanism hidden under the seat to highlight the design.',
    },
    {
      id: 7,
      name: 'VICKLEBY',
      image: require('../assets/images/products/offers/pic7.png'),
      type: 'Floor lamp, beige/handmade',
      price: '1,290',
      category: 'Bar Tables',
      short_desc:
        'This floor lamp with a handmade lampshade in rice paper spreads a soft, cosy light that makes your room feel inviting. It also takes up little space thanks to its oval shape and neat metal legs.',
      uid: '104.844.84',
      desc: 'You can create a soft, cosy atmosphere in your home with a paper lamp that spreads a diffused and decorative light.',
    },
    {
      id: 8,
      name: 'NODELAND',
      image: require('../assets/images/products/offers/pic8.png'),
      type: 'Bedside table, black-brown',
      price: '1,290',
      category: 'Bedside tables',
      short_desc:
        'With this bedside table, you can have both magazines and a glass of water within reach when you go to bed. If you like the simple expression, the NODELAND series has more furniture in the same style.',
      uid: '004.943.70',
      desc: 'The open shelf makes it easy for you to see and reach your things.',
    },
    {
      id: 9,
      name: 'SKRUVBY',
      image: require('../assets/images/products/offers/pic10.png'),
      type: 'Coffee table, black-blue',
      price: '4,990',
      category: 'Coffee tables',
      short_desc:
        'The SKRUVBY series has a traditional look with solitaire pieces of furniture that can be coordinated. Look at this coffee table as a blank canvas, add open and closed storage and create your artwork!',
      uid: '305.319.84',
      desc: 'The furniture in the SKRUVBY series is designed to go well together. Combine and match them as you like or use each piece of furniture as a beautiful solitaire.',
    },
    {
      id: 11,
      name: 'JOKKMOKK',
      image: require('../assets/images/products/offers/pic11.png'),
      type: 'Table and 4 chairs, antique stain',
      price: '16,490',
      category: 'Dining sets',
      short_desc:
        'A simple and sturdy set that’s perfect for your breakfast nook or smaller dining area. The solid pine holds up well over time and will endure all the family meals and activities around the table.',
      uid: '603.658.03',
      desc: 'Easy to bring home since the whole dining set is packed in one box. The wood expression and design of the backrest bring a traditional look to the room. Enhance the comfort by adding soft chair pads that fit the seat perfectly.',
    },
    {
      id: 12,
      name: 'IKORNNES',
      image: require('../assets/images/products/offers/pic12.png'),
      type: 'Standing mirror, ash',
      price: '6,990',
      category: 'Racks & stands',
      short_desc:
        'Tired in the morning? Then hang tomorrow’s outfit behind the mirror and allow yourself with a few more minutes under the covers. The soft shapes and warm ash veneer create a cosy feeling in the room.',
      uid: '102.983.97',
      desc: 'Tired in the mornings? You can save time by hanging tomorrow’s outfit behind the mirror. To avoid clothes piles and extra loads of laundry, you can hang used clothes behind the mirror.',
    },
    {
      id: 10,
      name: 'SANDSBERG / ADDE',
      image: require('../assets/images/products/offers/pic9.png'),
      type: 'Table and 4 chairs, black/black',
      price: '6,790',
      category: 'Dining sets',
      short_desc:
        'A slim design that blends in without taking up too much visual space in the room, yet sturdy enough to hold up to everyday activities.',
      uid: '294.291.95',
      desc: "You can stack the chairs, so they take less space when you're not using them.",
    },
  ],
  armchair: [
    {
      id: 1,
      name: 'EKOLSUND',
      image: require('../assets/images/products/armchair/pic5.png'),
      type: 'Wing chair, grey',
      price: '30,990',
      uid: '692.971.88',
      category: 'Fabric armchairs',
      short_desc:
        'EKOLSUND recliner has soft rounded shapes which are sized to fit in even small spaces. Adjustable in three positions – so choose whether you want to sit upright, lean back or lie back for a nap.',
      desc: 'You can set this reclining armchair in 3 positions – upright, lean back and full recline – making it easy to adapt to various activities at home.',
    },
    {
      id: 2,
      name: 'REMSTA',
      image: require('../assets/images/products/armchair/pic3.png'),
      type: 'Wing chair, grey',
      price: '15,990',
      uid: '304.923.17',
      category: 'Fabric armchairs',
      short_desc:
        'With its classic expression, modern comfort and durable fabric, this grey wing chair will surely last for many cosy evenings at home, just like when we first launched it in the 1950s.',
      desc: 'You can really loosen up and relax in comfort because the high back on this chair provides extra support for your neck.',
    },
    {
      id: 3,
      name: 'OMTÄNKSAM',
      image: require('../assets/images/products/armchair/pic2.png'),
      type: 'Wing chair, grey',
      price: '15,990',
      uid: '304.923.17',
      category: 'Fabric armchairs',
      short_desc:
        'With its classic expression, modern comfort and durable fabric, this grey wing chair will surely last for many cosy evenings at home, just like when we first launched it in the 1950s.',
      desc: 'You can really loosen up and relax in comfort because the high back on this chair provides extra support for your neck.',
    },
    {
      id: 4,
      name: 'STRANDMON',
      image: require('../assets/images/products/armchair/pic4.png'),
      type: 'Wing chair, grey',
      price: '15,990',
      uid: '304.923.17',
      category: 'Fabric armchairs',
      short_desc:
        'With its classic expression, modern comfort and durable fabric, this grey wing chair will surely last for many cosy evenings at home, just like when we first launched it in the 1950s.',
      desc: 'You can really loosen up and relax in comfort because the high back on this chair provides extra support for your neck.',
    },
  ],
  cabinet: [
    {
      id: 1,
      name: 'BRIMNES',
      image: require('../assets/images/products/cupboard/pic1.png'),
      type: 'Cabinet with doors, black',
      price: '7,990',
      category: 'Cabinets',
      short_desc:
        'Small spaces demand smart storage. The BRIMNES series maximises the space in every unit, and with adjustable shelves, the storage possibilities are, if not endless, at least very big.',
      uid: '203.518.60',
      desc: 'Adjustable shelves, so you can customise your storage as needed.',
    },
    {
      id: 2,
      name: 'HAUGA',
      image: require('../assets/images/products/cupboard/pic2.png'),
      type: 'Cabinet with doors, black',
      price: '7,990',
      category: 'Cabinets',
      short_desc:
        'Small spaces demand smart storage. The BRIMNES series maximises the space in every unit, and with adjustable shelves, the storage possibilities are, if not endless, at least very big.',
      uid: '203.518.60',
      desc: 'Adjustable shelves, so you can customise your storage as needed.',
    },
    {
      id: 3,
      name: 'BILLY / HÖGBO',
      image: require('../assets/images/products/cupboard/pic4.png'),
      type: 'Cabinet with doors, black',
      price: '7,990',
      category: 'Cabinets',
      short_desc:
        'Small spaces demand smart storage. The BRIMNES series maximises the space in every unit, and with adjustable shelves, the storage possibilities are, if not endless, at least very big.',
      uid: '203.518.60',
      desc: 'Adjustable shelves, so you can customise your storage as needed.',
    },
    {
      id: 4,
      name: 'BILLY / OXBERG',
      image: require('../assets/images/products/cupboard/pic5.png'),
      type: 'Cabinet with doors, black',
      price: '7,990',
      category: 'Cabinets',
      short_desc:
        'Small spaces demand smart storage. The BRIMNES series maximises the space in every unit, and with adjustable shelves, the storage possibilities are, if not endless, at least very big.',
      uid: '203.518.60',
      desc: 'Adjustable shelves, so you can customise your storage as needed.',
    },
  ],
};

export default data;
